### ISSUE TITLE
Can you point me to where the 240x320 changes came from in this repo?

### ISSUE THREAD

**Issue by bdwilson** [alexgrach/KP3S#1]
Just curious if you came up with these patches on your own or if they were done by someone else.  I'd like to get this working on 2.1.2 as well.

**Comment by alexgrach** [comment]
2.1.2 does not work correctly on KP3S with GD32F303 MCU. You can check [kingroon-kp3s-debug](https://github.com/alexgrach/Marlin/tree/kingroon-kp3s-debug). I have portrait mode for 2.1.2, but it's outdated.

**Comment by alexgrach** [comment]
I've made it by my own. I like KP3S default screen placement, so I've made portrait mode for it.

**Comment by bdwilson** [comment]
Thank you for doing this; Also looks like you have the drivers in EPROM mode and have linear advance enabled.  Is that what is causing the issue with 2.1.2?

**Comment by alexgrach** [comment]
No. As I can remember, there was DMA problem with GD32 and it was fixed by jmz52 somehow [kingroon-kp3s-debug](https://github.com/jmz52/Marlin/tree/kingroon-kp3s-debug)
